[[keyboard.bindings]]
chars = "\u001B[48;5u"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[49;5u"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[50;5u"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[51;5u"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[52;5u"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[53;5u"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[54;5u"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[55;5u"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[56;5u"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[57;5u"
key = "Key9"
mods = "Control"

[colors]
transparent_background_colors = true

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
decorations = "none"
opacity = 0.8
blur = true

[keyboard]
